apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    app: api-monitoring-app
    name: frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-monitoring-app
      name: frontend-pod
  template:
    metadata:
      name: frontend-pod
      labels:
        app: api-monitoring-app
        name: frontend-pod
    spec:
      containers:
        - name: frontend
          image: nguyentankdb17/api-monitoring-app:frontend
          imagePullPolicy: Always
          ports:
          - containerPort: 80